#############################################################################
# Makefile for building: rb
# Generated by qmake (2.01a) (Qt 4.8.4) on: Tue Jun 3 21:22:37 2014
# Project:  rb.pro
# Template: app
# Command: /usr/bin/qmake -unix OBJECTS_DIR\ =\ ./obj MOC_DIR\ =\ ./moc -o Makefile rb.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Isrc -Isrc/motor -Imoc -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtGui -L/usr/lib64 -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/lpanel.cpp \
		src/main.cpp \
		src/preferencias.cpp \
		src/ventana.cpp \
		src/motor/motor.cpp moc/moc_lpanel.cpp \
		moc/moc_preferencias.cpp \
		moc/moc_ventana.cpp \
		qrc_recursos.cpp
OBJECTS       = obj/lpanel.o \
		obj/main.o \
		obj/preferencias.o \
		obj/ventana.o \
		obj/motor.o \
		obj/moc_lpanel.o \
		obj/moc_preferencias.o \
		obj/moc_ventana.o \
		obj/qrc_recursos.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		rb.pro
QMAKE_TARGET  = rb
DESTDIR       = 
TARGET        = rb

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_preferencias.h ui_ventana.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: rb.pro  /usr/share/qt4/mkspecs/default/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -unix OBJECTS_DIR\ =\ ./obj MOC_DIR\ =\ ./moc -o Makefile rb.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix OBJECTS_DIR\ =\ ./obj MOC_DIR\ =\ ./moc -o Makefile rb.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/rb1.0.0 || $(MKDIR) obj/rb1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/rb1.0.0/ && $(COPY_FILE) --parents src/lpanel.h src/preferencias.h src/ventana.h src/motor/motor.h obj/rb1.0.0/ && $(COPY_FILE) --parents recursos/recursos.qrc obj/rb1.0.0/ && $(COPY_FILE) --parents src/lpanel.cpp src/main.cpp src/preferencias.cpp src/ventana.cpp src/motor/motor.cpp obj/rb1.0.0/ && $(COPY_FILE) --parents forms/preferencias.ui forms/ventana.ui obj/rb1.0.0/ && (cd `dirname obj/rb1.0.0` && $(TAR) rb1.0.0.tar rb1.0.0 && $(COMPRESS) rb1.0.0.tar) && $(MOVE) `dirname obj/rb1.0.0`/rb1.0.0.tar.gz . && $(DEL_FILE) -r obj/rb1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_lpanel.cpp moc/moc_preferencias.cpp moc/moc_ventana.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_lpanel.cpp moc/moc_preferencias.cpp moc/moc_ventana.cpp
moc/moc_lpanel.cpp: src/motor/motor.h \
		src/lpanel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/lpanel.h -o moc/moc_lpanel.cpp

moc/moc_preferencias.cpp: ui_preferencias.h \
		src/preferencias.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/preferencias.h -o moc/moc_preferencias.cpp

moc/moc_ventana.cpp: ui_ventana.h \
		src/lpanel.h \
		src/motor/motor.h \
		src/preferencias.h \
		ui_preferencias.h \
		src/ventana.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/ventana.h -o moc/moc_ventana.cpp

compiler_rcc_make_all: qrc_recursos.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_recursos.cpp
qrc_recursos.cpp: recursos/recursos.qrc \
		recursos/imagenes/nada.png \
		recursos/imagenes/rosa.png \
		recursos/imagenes/verde.png \
		recursos/imagenes/amarilla.png \
		recursos/imagenes/nuevopj.png \
		recursos/imagenes/icono.png \
		recursos/imagenes/azul.png \
		recursos/imagenes/roja.png \
		recursos/imagenes/apagar.png \
		recursos/imagenes/preferencias.png
	/usr/bin/rcc -name recursos recursos/recursos.qrc -o qrc_recursos.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_preferencias.h ui_ventana.h
compiler_uic_clean:
	-$(DEL_FILE) ui_preferencias.h ui_ventana.h
ui_preferencias.h: forms/preferencias.ui
	/usr/bin/uic forms/preferencias.ui -o ui_preferencias.h

ui_ventana.h: forms/ventana.ui \
		src/lpanel.h \
		src/motor/motor.h
	/usr/bin/uic forms/ventana.ui -o ui_ventana.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

obj/lpanel.o: src/lpanel.cpp src/lpanel.h \
		src/motor/motor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/lpanel.o src/lpanel.cpp

obj/main.o: src/main.cpp src/ventana.h \
		ui_ventana.h \
		src/lpanel.h \
		src/motor/motor.h \
		src/preferencias.h \
		ui_preferencias.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/preferencias.o: src/preferencias.cpp src/preferencias.h \
		ui_preferencias.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/preferencias.o src/preferencias.cpp

obj/ventana.o: src/ventana.cpp src/ventana.h \
		ui_ventana.h \
		src/lpanel.h \
		src/motor/motor.h \
		src/preferencias.h \
		ui_preferencias.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ventana.o src/ventana.cpp

obj/motor.o: src/motor/motor.cpp src/motor/motor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/motor.o src/motor/motor.cpp

obj/moc_lpanel.o: moc/moc_lpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_lpanel.o moc/moc_lpanel.cpp

obj/moc_preferencias.o: moc/moc_preferencias.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_preferencias.o moc/moc_preferencias.cpp

obj/moc_ventana.o: moc/moc_ventana.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_ventana.o moc/moc_ventana.cpp

obj/qrc_recursos.o: qrc_recursos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_recursos.o qrc_recursos.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

